name:                hs-fly-io
version:             0.1.0.0
github:              "githubuser/hs-fly-io"
license:             MIT
author:              "Jerahmeel Cosinas"
maintainer:          "me@jerahmeelcosinas.net"
copyright:           "2022 Jerahmeel Cosinas"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-fly-io#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  hs-fly-io:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-fly-io

tests:
  hs-fly-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-fly-io
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
